# Generated by Django 4.0.4 on 2022-05-08 19:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.CharField(blank=True, choices=[('Btech 1st', 'Btech 1st'), ('Btech 2nd', 'Btech 2nd'), ('Btech 3rd', 'Btech 3rd'), ('Btech 4th', 'Btech 4th'), ('Btech 5th', 'Btech 5th'), ('Btech 6th', 'Btech 6th'), ('Btech 7th', 'Btech 7th'), ('Btech 8th', 'Btech 8th')], max_length=10, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit', models.CharField(blank=True, choices=[('Unit 1', 'Unit 1'), ('Unit 2', 'Unit 2'), ('Unit 3', 'Unit 3'), ('Unit 4', 'Unit 4'), ('Assignment', 'Assignment')], max_length=10, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=50)),
                ('subcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters are allowed.')])),
                ('desc', models.TextField(max_length=1000)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.semester')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField(auto_now_add=True)),
                ('file_upload', models.FileField(upload_to='')),
                ('uploaded_by', models.CharField(max_length=60)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.subject')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.unit')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
